FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer
ENV MSSQL_MEMORY_LIMIT_MB=2048
ENV MSSQL_VISIBLE_CPUS=0-1

COPY database/sqlserver-limit-cpus.sh /sqlserver-limit-cpus.sh

EXPOSE 1433
ENTRYPOINT ["bash", "/sqlserver-limit-cpus.sh"]
